"""empty message

Revision ID: e3fe195749cf
Revises: None
Create Date: 2016-10-27 14:04:27.149712

"""

# revision identifiers, used by Alembic.
revision = 'e3fe195749cf'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('sent_date', sa.DateTime(), nullable=True),
    sa.Column('to', sa.Text(), nullable=True),
    sa.Column('brief_description', sa.Text(), nullable=True),
    sa.Column('rest_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mails')
    ### end Alembic commands ###
